// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkjizfOr1Apny6LB6fQzFcmQPUzZhfMJM',
    appId: '1:77725405974:web:253aeaa1cd44f825773637',
    messagingSenderId: '77725405974',
    projectId: 'artificial-3fd2e',
    authDomain: 'artificial-3fd2e.firebaseapp.com',
    databaseURL: 'https://artificial-3fd2e-default-rtdb.firebaseio.com',
    storageBucket: 'artificial-3fd2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsD7tZm6Ae8Yw-O-0p5o_UhvGf9jJSpA4',
    appId: '1:77725405974:android:59e14005d305a9fe773637',
    messagingSenderId: '77725405974',
    projectId: 'artificial-3fd2e',
    databaseURL: 'https://artificial-3fd2e-default-rtdb.firebaseio.com',
    storageBucket: 'artificial-3fd2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGo44RsBqzvFeNxInGI6XnwXBgmGc0H0',
    appId: '1:77725405974:ios:a6d0f9ff29561f53773637',
    messagingSenderId: '77725405974',
    projectId: 'artificial-3fd2e',
    databaseURL: 'https://artificial-3fd2e-default-rtdb.firebaseio.com',
    storageBucket: 'artificial-3fd2e.firebasestorage.app',
    iosBundleId: 'com.example.artificial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGo44RsBqzvFeNxInGI6XnwXBgmGc0H0',
    appId: '1:77725405974:ios:a6d0f9ff29561f53773637',
    messagingSenderId: '77725405974',
    projectId: 'artificial-3fd2e',
    databaseURL: 'https://artificial-3fd2e-default-rtdb.firebaseio.com',
    storageBucket: 'artificial-3fd2e.firebasestorage.app',
    iosBundleId: 'com.example.artificial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkjizfOr1Apny6LB6fQzFcmQPUzZhfMJM',
    appId: '1:77725405974:web:36b93e4fbc31a55f773637',
    messagingSenderId: '77725405974',
    projectId: 'artificial-3fd2e',
    authDomain: 'artificial-3fd2e.firebaseapp.com',
    databaseURL: 'https://artificial-3fd2e-default-rtdb.firebaseio.com',
    storageBucket: 'artificial-3fd2e.firebasestorage.app',
  );
}
